rails/SISMU/config/routes.rb
Rails.application.routes.draw do
  get 'configs/index'
  get 'configs/new'
  namespace :emfacturas do
    get 'emdetalles/create'
  end

  get 'emfacturas/index'
  get 'emfacturas/show'
  get 'emfacturas/new'

  # Clientes
  resources :clients

  # MATERIALES
  resources :materials do
    resources :materials_productos, module: :materials
  end

  # CATEGORIA
  resources :categories do
    resources :categories_productos, module: :categories
  end

  #PRODUCTO
  resources :productos do
    resources :categories_productos,module: :productos
  end

  # PEDIDOS FACTURAS
  resources :facturas do
    resources :detalles, module: :facturas, only: [:create ,:destroy]
  end
  
  #colors
  resources :colors

  resources :profiles

  #artesanos
  resources :artesanos
  
  #produccion
  resources :productions do
    resources :dproductions, module: :productions, only:[:create, :destroy]
  end
 
  #empresas
  resources :empresas

  #facturas empresas

  resources :emfacturas do
    resources :emdetalles, module: :emfacturas, only:[:create, :destroy]
  end
  #configuración
  resources :configs
  #HOME
  root to: "home#index"
  
  #DEVISE
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

rails/SISMU/app/models/factura.rb
class Factura < ApplicationRecord
  belongs_to :client
  has_many :detalles, dependent: :destroy
  has_many :productos, through: :detalles
  validates :fref, presence: { :message => "Este campo es obligatorio"  }
  validates :fref, uniqueness: { :message => "el numero de factura ya está en uso" }

  def final
    detalles.sum(&:valor)
  end
  def iva
    self.final*0.19
  end
  def final_total
    self.final + self.iva
  end
  def self.search(search)
    if search
     includes(:client).where( ["fref LIKE ? or nombre_cli LIKE ? or apellido_cli LIKE ?  ", "%#{search}%", "%#{search}%", "%#{search}%" ]  ).references(:client)
    else
        unscoped
    end
  end
end

rails/SISMU/app/controllers/facturas/detalles_controller.rb
class Facturas::DetallesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_factura

    def create
        @detalle = @factura.detalles.new(detalle_params)
        @detalle.save
        redirect_to factura_path(@factura)       
    end
    def destroy 
        @detalle = @factura.detalles.find(params[:id]).destroy
        redirect_to factura_path(@factura)   
    end
      
    private

    def detalle_params
        params.require(:detalle).permit(:producto_id, :cantidad,:extra, :valor,:fechafin, color_ids: []  )
    end

    def set_factura
        @factura = Factura.find(params[:factura_id])
    end
end

rails/SISMU/app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_factura, only: [:show]

  def new
    @factura = Factura.new
    authorize @factura
  end

  def show
    @detalles = @factura.detalles
    authorize @factura
    @detalle = Detalle.new
    @color = Color.new
    @total = @factura.detalles.sum(:valor)
    respond_to do |format|
      format.html
      format.pdf do
        render template: "facturas/factura", pdf: "factura-cliente -#{@factura.id}" ,layout:"pdf" # Excluding ".pdf" extension.
      end
    end
  end

  def edit
    @factura = Factura.find(params[:id])
    authorize @factura
  end


  def update
    @factura = Factura.find(params[:id])
    if @factura.update(factura_params)
      flash[:notice] = "Se actualizó correctamente."
      redirect_to facturas_path
    else
        render :edit
    end
  end

  def index
    @facturas = Factura.all()
    
    authorize @facturas
    @q = Factura.ransack(params[:q])
    
    @facturas = if params[:q]
       @q.result(distinct: true).paginate(:per_page => 20, :page => params[:page])  
      else
        Factura.search(params[:search]).paginate(:per_page => 20, :page => params[:page]) 
      end

  end

  def create
    @factura = Factura.new(factura_params)
    if @factura.save
      flash[:notice] = "Se creo correctamente."
      redirect_to factura_path(@factura)
    else
      render :new
    end
  end
def destroy 
  @factura = Factura.find(params[:id]).destroy
  redirect_to facturas_path
end
  private

  def factura_params
    params.require(:factura).permit(:client_id, :fechafin, :fref)
  end

  def set_factura
    @factura = Factura.find(params[:id])
  end
end

rails/SISMU/app/helpers/facturas/detalles_helper.rb
module Facturas::DetallesHelper
end

rails/SISMU/app/helpers/facturas_helper.rb
module FacturasHelper
end

rails/SISMU/app/views/facturas/_factura.html.erb
<tr>
  <td data-label="N° Factura" class="centrar red">
    <%= factura.fref %>
  </td>
  <td data-label="Nombre" class="centrar red">
    <%= factura.client.nombre_completo %>
  </td>
  <td data-label="Correo" class="centrar red">
    <%= factura.client.correo_cli %>
  </td>
  <td data-label="Fecha" class="centrar red">
    <%= factura.created_at %>
  </td>

  <td data-label="Accion" class="botones red">
    <%= link_to factura_url(factura.id) do %>
       <button class="ver">Ver</button>
    <% end %>
  
    <%= button_to "Eliminar",  factura_path(factura), method: :delete, class: "btn_borrar, eliminar", onclick: "return confirmDestroy('¿Deseas eliminar esta factura?')" %>
    <%= button_to "PDF" ,factura_url(factura.id, :format => :pdf), class:"btn_pdf", method: :get %>
    
  </td>
</tr>

<script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>

rails/SISMU/app/views/facturas/_form.html.erb
<%= simple_form_for @factura do |f| %>
  <main class="clientesNew sombra" >
    <section class="botonVolverNew"><%= link_to "Volver", facturas_url, class: "volverNew" %></section>
    <h1>Registrar Factura</h1>

    <section class="informacionNewConf">
      <div>
        <%= f.label :fref, "Ref. factura",class: 'is-required'  %>
        <%= f.input_field :fref, class: 'input_clientes'%>
      
      </div>
          <% if @factura.errors[:fref].any? %>
            <p class="text-danger"><%= @factura.errors[:fref].first %></p>
          <% end %>
      <div class="errorShow">
        <%= f.label :client, "Cliente", class: 'is-required' %>
        <%= f.association :client, label_html: { hidden: true }, label_method: :nombre_completo, error: "Seleccionar" %>
      </div>

      <div class="fechaFacturaNew">
        <%= f.label :fechafin, "Fecha de entrega"%>
        <%= f.input_field :fechafin%>
      </div>
    </section>

    <section class="botonesNew">
      <%= f.button :submit, "Crear Factura", class:"crearClientes" %>
    </section>   
  </main>
<% end %>

rails/SISMU/app/views/facturas/edit.html.erb
<%= render "form" %>

rails/SISMU/app/views/facturas/factura.pdf.erb
 
<div class="mt-6 border" >
  <div class="container">
    
  <div class="card border-0 pt-5 " style="height: 18rem; ">
      <%= image_tag wicked_pdf_asset_base64('logo_completo_sandra_munoz.png'), class:" po  " %>
      <h2 class="card_title">DATOS DEL CLIENTE</h2>

  
          <div class ="card_body" >
            <b>Ref factura: </b>
            <%= @factura.fref %>
            <br>
            <b>Nombre: </b>
            <%= @factura.client.nombre_completo %>
            <br>
            <b>Correo: </b>
            <%= @factura.client.correo_cli %>
            <br>
            <b>Dirección: </b>
            <%= @factura.client.cli_envio%>
          </div>
          

  </div>
</div>
 

</div>
  <br>
    <div class="mt-5">
      <h2 >DATOS DE LOS PRODUCTOS</h2>
      <table class="table table-striped table-bordered ">
          <thead class="">
              <tr class="">
                  <th> Fecha de entrega</th>
                  <td colspan="6"><%= @factura.fechafin %></td>
              </tr>
              <tr class="">
                  <th>Ref</th>
                  <th>Producto</th>
                  <th>Precio uni.</th>
                  <th>Color</th>
                  <th>detalles</th>
                  <th>Cantidad</th>
                  <th>Precio total</th>

              </tr>        
          </thead>    
          <tbody class="">

          <% @detalles.each do |detalle| %>

              <tr class="">
                  <td><%= detalle.producto.referencia_pro %></td>
                  <td><%= detalle.producto.nombre_pro %></td>
                  <td><%= number_to_currency detalle.precio%></td>
                  <td >
                      <% detalle.colors.each do |d| %>
                          <%= d.tipo%>
                      <%end%>
                  </td> 
                  <td><%= detalle.extra %></td>
                  <td><%= detalle.cantidad %></td>
                  <td><%= number_to_currency detalle.valor %></td>
              </tr>
          <% end %>
          <tr>
              <th >Precio subtotal: </th>
              <td colspan="6"><%=number_to_currency @factura.final %></td>   
          </tr>
              <tr>
              <th >Impuesto por iva: </th>
              <td colspan="6"><%=number_to_currency @factura.iva %></td>   
          </tr>
              <tr>
              <th class="bg-warning" >Precio final: </th>
              <td colspan="6"><%=number_to_currency @factura.final_total %></td>   
          </tr>


          </tbody>
      </table>

    </div>


<style>
  .po{
    position: absolute;
     top: 6%%;
    left: 70%%;
  }
</style>

rails/SISMU/app/views/facturas/index.html.erb
<main class="container sombra">
    <section class="productos">
        <%# <div class="box">
            <%= form_tag facturas_path, :method => 'get' do %
                <p>
                    <%= text_field_tag :search, params[:search] %
                    <%= submit_tag "Buscar", :id => nil  %
                </p>
            <% end %
        </div> %>

        <div class="buscador_client">
          <div class="prueba_client">
            <%= form_tag facturas_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search], placeholder: "Buscar"%>
              <div class="btn_buscar_client">
                <button class="btn_borrar">
                  <%= image_tag "iconos/buscar_blanco", :referencia_pro => nil, class: "logoBuscar_client" %>
                </button>
              </div>
            <% end %>
          </div>
        </div>

        <h1 class="clientes__titulo">Facturas</h1>
        <div class="clientes__nuevo">
            <%= link_to new_factura_url do %>
                <p>Nuevo</p>
            <% end %>
        </div>
    </section>

  <section class="clientesTable">
    <table>
      <thead>
        <tr>
          <th><%= sort_link(@q, :fref,"N° Factura ", default_order: :desc, class:"white") %></th>
          <th><%= sort_link(@q, :client_nombre_cli," Nombre", default_order: :desc, class:"white") %></th>
          <th><%= sort_link(@q, :client_correo_cli,"Correo", default_order: :desc, class:"white") %></th>
          <th><%= sort_link(@q, :created_at,"Fecha de creación", default_order: :desc, class:"white")%></th>
          <th colspan="3">Acción</th>
        </tr>
      </thead>
      <tbody>
        <%= render @facturas %>
      </tbody>

    </table>
  </section>
  <div class="digg_pagination">
    <%= will_paginate(@facturas,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0) %>
  </div>
</main>

rails/SISMU/app/views/facturas/new.html.erb
<%= render "form" %>

rails/SISMU/app/views/facturas/show.html.erb
<div class="container_facturas">
  <section class = "botonEliminarShow">
    <%= button_to "Eliminar factura",  @factura, method: :delete, class: "btn_borrar, eliminar_fac", onclick: "return confirmDestroy('¿Deseas eliminar esta factura?')" %>
  </section>

  <div class="volver_facturas">
    <button class="btn_back">
      <%= link_to "Volver" , facturas_url %>
    </button>
  </div>

  <div class="facturas_grid">
    <div class="facturas_cliente sombra">
      <h2 id="titulo_factura">Datos Cliente</h2>
      <b>Id: </b>
      <%= @factura.fref %>
      <br>
      <b>Nombre: </b>
      <%= @factura.client.nombre_completo %>
      <br>
      <b>Correo: </b>
      <%= @factura.client.correo_cli %>
      <br>
      <b>Dirección: </b>
      <%= @factura.client.cli_envio%>
    </div>

      <div class="formulario_facturas_productos sombra selectFacturas">
        <h2 id="titulo_factura">Datos Producto</h2>
        <%= simple_form_for [@factura, @detalle] do |f| %>
            <%= f.association :producto, label_method: :buscar_producto, label: "Nombre del producto: " %>
            <%= f.label :cantidad, "Cantidad:", label: "Cantidad:", class: "inputCantidad" %>
            <%= f.input_field :cantidad, class: "inputCantidad" %>
                <% if @detalle.errors[:cantidad].any? %>
                  <span class="text-danger"><%= @detalle.errors[:cantidad].first %></span>
                  <br>
                <% end %>
                <div>
                
                  <%= f.label :extra, "detalles extras:", label: "detalles:"%>
                  <%= f.input_field :extra, class: 'input_clientes' %>
                </div>
            <%= f.association :colors,as: :check_boxes, label_method: :tipo, label: "Colores: ", class: "colorSelect" %>
          
            <%= f.button :submit, "Añadir", class: "factura_nuevo" %>
            
        <% end %>
      </div>
  </div>

    <div class="formulario_facturas_facturas sombra productosTable">
      <section class = "botonEliminarShow">
        <%= link_to "Imprimir PDF" ,factura_url(@factura, :format => :pdf) %>
   
      </section>
      <h2 id="titulo_factura">Factura del Cliente</h2>
      <table>
          <thead>
              <tr>
                  <th> Fecha de entrega</th>
                  <td colspan="7"><%= @factura.fechafin %></td>
              </tr>
              <tr>
                  <th>Ref</th>
                  <th>Producto</th>
                  <th>Precio uni.</th>
                  <th>Color</th>
                  <th>detalles</th>
                  <th>Cantidad</th>
                  <th>Precio total</th>
                  <th>Acción</th>
              </tr>        
          </thead>    
          <tbody>

          <% @detalles.each do |detalle| %>

              <tr>
                  <td><%= detalle.producto.referencia_pro %></td>
                  <td><%= detalle.producto.nombre_pro %></td>
                  <td><%= number_to_currency detalle.precio%></td>
                  <td >
                      <% detalle.colors.each do |d| %>
                          <%= d.tipo%>
                      <%end%>
                  </td> 
                  <td><%= detalle.extra %></td>
                  <td><%= detalle.cantidad %></td>
                  <td><%= number_to_currency detalle.valor %></td>
                  <td><%= button_to "Eliminar", factura_detalle_path(@factura, detalle), method: :delete, class: "btn_borrar, eliminar" %></td>
              </tr>
          <% end %>
          <tr>
              <th >Precio subtotal: </th>
              <td colspan="7"><%=number_to_currency @factura.final %></td>   
          </tr>
              <tr>
              <th >Impuesto por iva: </th>
              <td colspan="7"><%=number_to_currency @factura.iva %></td>   
          </tr>
              <tr>
              <th >Precio final: </th>
              <td colspan="7"><%=number_to_currency @factura.final_total %></td>   
          </tr>


          </tbody>
      </table>
    </div>
</div>

<script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>