rails/SISMU/config/routes.rb
Rails.application.routes.draw do
  get 'configs/index'
  get 'configs/new'
  namespace :emfacturas do
    get 'emdetalles/create'
  end

  get 'emfacturas/index'
  get 'emfacturas/show'
  get 'emfacturas/new'

  # Clientes
  resources :clients

  # MATERIALES
  resources :materials do
    resources :materials_productos, module: :materials
  end

  # CATEGORIA
  resources :categories do
    resources :categories_productos, module: :categories
  end

  #PRODUCTO
  resources :productos do
    resources :categories_productos,module: :productos
  end

  # PEDIDOS FACTURAS
  resources :facturas do
    resources :detalles, module: :facturas, only: [:create ,:destroy]
  end
  
  #colors
  resources :colors

  resources :profiles

  #artesanos
  resources :artesanos
  
  #produccion
  resources :productions do
    resources :dproductions, module: :productions, only:[:create, :destroy]
  end
 
  #empresas
  resources :empresas

  #facturas empresas

  resources :emfacturas do
    resources :emdetalles, module: :emfacturas, only:[:create, :destroy]
  end
  #configuración
  resources :configs
  #HOME
  root to: "home#index"
  
  #DEVISE
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

rails/SISMU/app/models/artesano.rb
class Artesano < ApplicationRecord

    validates :nombre, :apellido, :id, :tel, presence: {:message => "«Este campo es obligatorio»"}
    validates :nombre,:apellido,  format: { with: /\A[a-zA-ZÀ-ÿ]+\z/, :message => "«Se permiten solo letras» (no se permiten carácteres especiales o espacios)" }
    validates :id, uniqueness: {:message => "«Este número de identificación  ya se encuentra en uso»"},length: {  in:7.. 10, :message=>"«Debe contener entre 7 y 10 digitos numéricos»" }
    
    # nuevas validaciones actualizacion version 1.2

    validates :tel, length: { is: 10, :message => "«Introduzca un numero de telefono válido» (El número de telefono solo puede tener 10 digitos)" } 
    validates :id, :tel, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 99999999999, :message => "«No se permiten números negativos»"  }
    
    
    has_many :dproductions, dependent: :destroy
    has_many :production, through: :dproductions

    def nombre_completo
        "#{id}- #{nombre} #{apellido}"
    end
    def nombre_apellido
        "#{nombre} #{apellido}"
    end
    def self.search(search)
        if search
          where( ["id LIKE  ? or nombre LIKE ? ", "%#{search}%","%#{search}%"]  )
        else
            unscoped
        end
      end

end

rails/SISMU/app/controllers/artesanos_controller.rb
class ArtesanosController < ApplicationController
  before_action :authenticate_user!
  def index
   
  
    @artesanos = Artesano.all()
    authorize @artesanos
    @q = Artesano.ransack(params[:q])
    
    @artesanos= if params[:q]
       @q.result(distinct: true).paginate(:per_page => 20, :page => params[:page])  
      else
        Artesano.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
      end

  end
  def show
    @artesano = Artesano.find(params[:id])
    authorize @artesano
  end
  
  def new
    @artesano = Artesano.new
    authorize @artesano
  end

  def create
    @artesano = Artesano.new(artesano_params)
    if @artesano.save
      flash[:notice] = "Se creó correctamente."
      redirect_to artesanos_path
    else
      render :new
    end
  end
  
  def edit
    @artesano = Artesano.find(params[:id])
    authorize @artesano
  end


  def update
    @artesano = Artesano.find(params[:id])
    if @artesano.update(artesano_params)
      flash[:notice] = "Se actualizó correctamente."
      redirect_to artesanos_path
    else
        render :edit
    end
  end

  def destroy
    @artesano = Artesano.find(params[:id]).destroy
    redirect_to artesanos_path

  end

  private

    def artesano_params
      params.require(:artesano).permit(:id, :nombre, :snombre, :apellido, :sapellido, :tel)
    end
end

rails/SISMU/app/helpers/artesanos_helper.rb
module ArtesanosHelper
end

rails/SISMU/app/views/artesanos/_artesano.html.erb
<tr>
    <td data-label="Cedula" class="centrar seaWater">
        <%= artesano.id %>
    </td>

    <td data-label="Primer Nombre" class="centrar seaWater">
        <%= artesano.nombre %>
    </td>

    <td data-label="Primer Apellido" class="centrar seaWater">
        <%= artesano.apellido %>
    </td>


    <td data-label="Accion" class="botones seaWater">
       <%= link_to artesano_url(artesano) do %>
        <button class="ver">Ver</button>
        <% end %>

      <%= link_to edit_artesano_url(artesano) do %>
        <button class="editar">Editar</button>
      <% end %>
      <%= button_to "Eliminar",artesano_path(artesano), method: :delete, class: "btn_borrar, eliminar", onclick: "return confirmDestroy('¿Deseas eliminar este artesano?')" %>

    
    </td>
</tr>

<script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>

rails/SISMU/app/views/artesanos/_form.html.erb
<%= simple_form_for @artesano do |f| %>
<main class = "artesanosNew sombra">

    <section class="botonVolverNew"><%= link_to "Volver", artesanos_url, class: "volverNew" %></section>
    <h1>Registrar Artesano</h1>

    <section class="informacionNew">
        <div>
            <%= f.label :id, "Cedula ", class:"input_artesano is-required" %>
            <%= f.input_field :id, class: 'input_artesano' , class:"label_artesano1" %>
            <% if @artesano.errors[:id].any? %>
                <p class="text-danger"><%= @artesano.errors[:id].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Nombre ", class:"input_artesano is-required" %>
            <%= f.input_field :nombre, class: 'input_artesano' , class:"label_artesano2" %>
            <% if @artesano.errors[:nombre].any? %>
                <p class="text-danger"><%= @artesano.errors[:nombre].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Segundo Nombre ", class:"input_artesano" %>
            <%= f.input_field :snombre,class: 'input_artesano' , class:"label_artesano3" %>
            <% if @artesano.errors[:snombre].any? %>
                <p class="text-danger"><%= @artesano.errors[:snombre].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Apellido ", class:"input_artesano is-required" %>
            <%= f.input_field :apellido, class: 'input_artesano' , class:"label_artesano2" %>
            <% if @artesano.errors[:apellido].any? %>
                <p class="text-danger"><%= @artesano.errors[:apellido].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Segundo Apellido ", class:"input_artesano" %>
            <%= f.input_field :sapellido, class: 'input_artesano' , class:"label_artesano3" %>
            <% if @artesano.errors[:sapellido].any? %>
                <p class="text-danger"><%= @artesano.errors[:sapellido].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Telefono ", class:"input_artesano is-required" %>
            <%= f.input_field :tel, class: 'input_artesano', class:"label_artesano2" %>
            <% if @artesano.errors[:tel].any? %>
                <p class="text-danger"><%= @artesano.errors[:tel].first %></p>
            <% end %>
        </div>
    </section>
        
     <section class="botonesNew">
        <%= f.button :submit,"Crear", class:"crearArtesanos"%>
    </section>    
</main>
<% end %>

rails/SISMU/app/views/artesanos/edit.html.erb
<%= simple_form_for @artesano do |f| %> <br>
<main class = "artesanosNew sombra">

    <section class="botonVolverNew"><%= link_to "Volver", artesanos_url, class: "volverNew" %></section>
    <h1>Editar Artesano</h1>

    <section class="informacionNew">
        <div>
            <%= f.label :id, "Cedula "%>
            <%= f.input_field :id, :disabled => true, class: "idBloquear"%>
            <% if @artesano.errors[:id].any? %>
                <p class="text-danger"><%= @artesano.errors[:id].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Nombre " %>
            <%= f.input_field :nombre %>
            <% if @artesano.errors[:nombre].any? %>
                <p class="text-danger"><%= @artesano.errors[:nombre].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Segundo Nombre "%>
            <%= f.input_field :snombre %>
        </div>

        <div>
            <%= f.label :id, "Apellido "%>
            <%= f.input_field :apellido %>
            <% if @artesano.errors[:apellido].any? %>
                <p class="text-danger"><%= @artesano.errors[:apellido].first %></p>
            <% end %>
        </div>

        <div>
            <%= f.label :id, "Segundo Apellido "%>
            <%= f.input_field :sapellido%>
        </div>

        <div>
            <%= f.label :id, "Telefono " %>
            <%= f.input_field :tel %>
        </div>
    </section>
        
     <section class="botonesNew">
        <%= f.button :submit,"Actualizar", class:"crearArtesanos"%>
    </section>    
</main>
<% end %>

rails/SISMU/app/views/artesanos/index.html.erb
<main class="container sombra">
    <section class="productos">
        <%# <div class="box">
            <%= form_tag artesanos_path, :method => 'get' do %
              <p>
                <%= text_field_tag :search, params[:search] %
                <%= submit_tag "Buscar", :id => nil  %
              </p>
            <% end %
        </div> %>

        <div class="buscador_artesanos">
          <div class="prueba_artesanos">
            <%= form_tag artesanos_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search], placeholder: "Buscar"%>
              <div class="btn_buscar_artesanos">
                <button class="btn_borrar">
                  <%= image_tag "iconos/buscar_blanco", :referencia_pro => nil, class: "logoBuscar_artesanos" %>
                </button>
              </div>
            <% end %>
          </div>
        </div>

        <h1 class="artesanos__titulo">Artesanos</h1>
        <%= link_to new_artesano_url do %>
          <div class="artesanos__nuevo">
            <p>Nuevo</p>
          </div>
        <% end %>
    </section>

    <section class="artesanosTable">
        <table>
            <thead>
                <tr>
                <th><%= sort_link(@q, :id,"Cedula", default_order: :desc, class:"white") %></th>
                <th><%= sort_link(@q, :nombre,"Primer Nombre", default_order: :desc, class:"white") %></th>
                <th><%= sort_link(@q, :apellido,"Primer Apelldio ", default_order: :desc, class:"white") %></th>
                <th colspan="3">Acción</th>
                </tr>
            </thead>
            <tbody>
                <%= render @artesanos%>
            </tbody>
        </table>
    </section>

  <div class="digg_pagination">
    <%= will_paginate(@artesanos,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0) %>
  </div> 

</main>

rails/SISMU/app/views/artesanos/show.html.erb
<main class="artesanosShow sombra">

     <section class = "botonEliminarShow">
          <%= button_to "Eliminar",@artesano, method: :delete, class: "btn_borrar, eliminar", onclick: "return confirmDestroy('¿Deseas eliminar este registro?')" %>
     </section>

     <h1>Información Artesano</h1>


     <section class= "informacionClientes">
        <div>
             <label>Cedula</label>
             <input type="text" value="<%= @artesano.id %>" name="cantidad" id="cantidad" disabled=»disabled» />
        </div>
        <div>
             <label>Telefono</label>
             <input type="text" value="<%= @artesano.tel%>" name="cantidad" id="cantidad" disabled=»disabled» />
        </div>
        
    </section>

    <section class= "informacionClientes">
        <div>
             <label>Primer Nombre</label>
             <input type="text" value="<%= @artesano.nombre %>" name="cantidad" id="cantidad" disabled=»disabled» />
        </div>
        <div>
             <label>Segundo Nombre</label>
             <input type="text" value="<%= @artesano.snombre %>" name="cantidad" id="cantidad" disabled=»disabled» />
        </div>
    </section>

    <section class= "informacionClientes">
        <div>
             <label>Primer Apellido</label>
             <input type="text" value="<%= @artesano.apellido %>" name="cantidad" id="cantidad" disabled=»disabled» />
        </div>
         <div>
             <label>Segundo Apellido</label>
             <input type="text" value="<%= @artesano.sapellido %>" name="cantidad" id="cantidad" disabled=»disabled» />
        </div>
    </section>

    <section class="botonVolver"><%= link_to "Volver", artesanos_url, class: "volver" %></section>

</main>
<script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>