rails/SISMU/config/routes.rb
Rails.application.routes.draw do
  get 'configs/index'
  get 'configs/new'
  namespace :emfacturas do
    get 'emdetalles/create'
  end

  get 'emfacturas/index'
  get 'emfacturas/show'
  get 'emfacturas/new'

  # Clientes
  resources :clients

  # MATERIALES
  resources :materials do
    resources :materials_productos, module: :materials
  end

  # CATEGORIA
  resources :categories do
    resources :categories_productos, module: :categories
  end

  #PRODUCTO
  resources :productos do
    resources :categories_productos,module: :productos
  end

  # PEDIDOS FACTURAS
  resources :facturas do
    resources :detalles, module: :facturas, only: [:create ,:destroy]
  end
  
  #colors
  resources :colors

  resources :profiles

  #artesanos
  resources :artesanos
  
  #produccion
  resources :productions do
    resources :dproductions, module: :productions, only:[:create, :destroy]
  end
 
  #empresas
  resources :empresas

  #facturas empresas

  resources :emfacturas do
    resources :emdetalles, module: :emfacturas, only:[:create, :destroy]
  end
  #configuración
  resources :configs
  #HOME
  root to: "home#index"
  
  #DEVISE
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

rails/SISMU/app/models/client.rb
class Client < ApplicationRecord
    # has_many :productos, through: :pedidos, dependent: :destroy
    has_many :facturas, dependent: :destroy

    def nombre_completo
        "#{id}- #{nombre_cli} #{apellido_cli}"
    end
    def cli_envio
      "#{direccion_cli}- #{ciudad}- #{barrio}"
    end
    validates :id, uniqueness: {  :message => "«Este número de identificación  ya se encuentra en uso»" }
    validates :id, :correo_cli, uniqueness: { :message => "«El correo electronico ingresado ya se encuentra en uso»" }
    validates :id, :nombre_cli, :apellido_cli, :tel_cli, :direccion_cli, presence: { :message => "«Este campo es obligatorio»"  }
    validates :nombre_cli, :apellido_cli, format: { with: /\A[a-zA-ZÀ-ÿ]+\z/, :message => "«Se permiten solo letras» (no se permiten carácteres especiales o espacios)" }
    validates :id, length: {  in:7.. 10, :message=>"«Debe contener entre 7 y 10 digitos numéricos»" }

    # nuevas validaciones actualizacion version 1.2
    
    validates :tel_cli, length: { is: 10, message: "«Introduzca un numero de telefono válido» (El número de telefono solo puede tener 10 digitos)" }
    validates :id, :tel_cli, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 99999999999, :message => "«No se permiten números negativos»"  }
   

    
    def self.search(search)
        if search
          where( ["id LIKE  ? or nombre_cli LIKE ? ", "%#{search}%","%#{search}%"]  )
        else
            unscoped
        end
      end
end

rails/SISMU/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  def index
    @clients = Client.all
    authorize @clients
    @q = Client.ransack(params[:q])
    
    @clients = if params[:q]
      @q.result(distinct: true).paginate(:per_page => 20, :page => params[:page])  
      else
        Client.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
      end
  end
  
  def show
    @client = Client.find(params[:id])
    authorize @client
  end
  
  def new
    @client = Client.new
    authorize @client

  end

  def create
    @client = Client.new(client_params)
    if @client.save 
      flash[:notice] = "Se creó correctamente."
      redirect_to clients_path
    else
      render :new
    end
  end
  
  def edit
    @client = Client.find(params[:id])
    authorize @client
  end


  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:notice] = "Se actualizó correctamente."
      redirect_to clients_path
    else
        render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id]).destroy
    redirect_to clients_path

  end

  private

    def client_params
      params.require(:client).permit(:id,:nombre_cli, :nombre2_cli, :apellido_cli, :apellido2_cli, :tel_cli, :correo_cli,:cedula_cli,:direccion_cli, :ciudad, :barrio)
    end
end

rails/SISMU/app/helpers/clients_helper.rb
module ClientsHelper
end

rails/SISMU/app/views/clients/_client.html.erb
<tr>
    <td data-label="Cedula" class="centrar red">
        <%= client.id %>
    </td>
    <td data-label="Primer Nombre" class="centrar red">
        <%= client.nombre_cli %>
    </td>
    
    <td data-label="Primer Apellido" class="centrar red">
        <%= client.apellido_cli %>
    </td>
  
   
    <td data-label="Accion" class="botones red">
        <%= link_to client_url(client) do %>
        <button class="ver">Ver</button>
        <% end %>
        <%= link_to edit_client_url(client) do %>
        <button class="editar">Editar</button>
        <% end %>
        <%= button_to "Eliminar",client_path(client), method: :delete, class: "btn_borrar, eliminar", onclick: "return confirmDestroy('¿Deseas eliminar este cliente?')" %>
    </td>
</tr>

<script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>

rails/SISMU/app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %> 
  <main class="clientesNew sombra">
    <section class="botonVolverNew">
      <%= link_to "Volver", clients_url, class: "volverNew" %>
    </section>
    <h1>Registrar Cliente</h1>

    <section class="informacionNew">
      <div>
        <%= f.label :id, "Cedula", class: 'is-required' %>
        <%= f.input_field :id, class: 'input_clientes'%>
        <% if @client.errors[:id].any? %>
          <p class="text-danger"><%= @client.errors[:id].first %></p>
        <% end %>
      </div>

      <div>
        <%= f.label :nombre_cli,"Nombre ", class: 'is-required'%>
        <%= f.input_field :nombre_cli, class: 'input_clientes' %>
        <% if @client.errors[:nombre_cli].any? %>
          <p class="text-danger"><%= @client.errors[:nombre_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :nombre2_cli,"Segundo Nombre "%>
        <%= f.input_field :nombre2_cli,  class: 'input_clientes2' %>
        <% if @client.errors[:nombre2_cli].any? %>
          <p class="text-danger"><%= @client.errors[:nombre2_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :apellido_cli,"Apellido ", class: 'is-required' %> 
        <%= f.input_field :apellido_cli, class: 'input_clientes' %>
        <% if @client.errors[:apellido_cli].any? %>
          <p class="text-danger"><%= @client.errors[:apellido_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :apellido2_cli,"Segundo Apellido "%> 
        <%= f.input_field :apellido2_cli,class: 'input_clientes2' %>
        <% if @client.errors[:apellido2_cli].any? %>
          <p class="text-danger"><%= @client.errors[:apellido2_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :tel_cli,"Télefono ", class: 'is-required' %> 
        <%= f.input_field :tel_cli, class: 'input_clientes'%>
        <% if @client.errors[:tel_cli].any? %>
          <p class="text-danger"><%= @client.errors[:tel_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :correo_cli,"Correo Eléctronico ", class: 'is-required' %> 
        <%= f.input_field :correo_cli, class: 'input_clientes2'%>
        <% if @client.errors[:correo_cli].any? %>
          <p class="text-danger"><%= @client.errors[:correo_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :direccion_cli,"Dirección ", class: 'is-required' %>
        <%= f.input_field :direccion_cli,class: 'input_clientes' %>
        <% if @client.errors[:direccion_cli].any? %>
          <p class="text-danger"><%= @client.errors[:direccion_cli].first%> </p>
        <% end %>
      </div>

      <div>      
        <%= f.label :ciudad,"Ciudad ", class: 'is-required' %> 
        <%= f.input_field :ciudad, class: 'input_clientes2'%>
        <% if @client.errors[:ciudad].any? %>
          <p class="text-danger"><%= @client.errors[:ciudad].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :barrio,"Barrio ", class: 'is-required' %> 
        <%= f.input_field :barrio, class: 'input_clientes2'%>
        <% if @client.errors[:barrio].any? %>
          <p class="text-danger"><%= @client.errors[:barrio].first %></p>
        <% end %>
      </div>
    </section>           
        
    <section class="botonesNew">
      <%= f.button :submit,"Crear", class:"crearClientes"%>
    </section>    
  </main>
<% end %>

rails/SISMU/app/views/clients/edit.html.erb
<%= simple_form_for @client do |f| %> 
  <main class="clientesNew sombra">
    <section class="botonVolverNew"><%= link_to "Volver", clients_url, class: "volverNew" %></section>
    <h1>Editar Cliente</h1>


    <section class="informacionNew">
      <div>
        <%= f.label :id, "Cedula"%>
        <%= f.input_field :id, :disabled => true, class: "idBloquear" %>
        <% if @client.errors[:id].any? %>
          <p class="text-danger"><%= @client.errors[:id].first %></p>
        <% end %>
      </div>

        <div>
          <%= f.label :nombre_cli,"Nombre "%>
          <%= f.input_field :nombre_cli %>
          <% if @client.errors[:nombre_cli].any? %>
            <p class="text-danger"><%= @client.errors[:nombre_cli].first %></p>
          <% end %>
        </div>

      <div>      
        <%= f.label :nombre2_cli,"Segundo Nombre "%>
        <%= f.input_field :nombre2_cli %>
      </div>

      <div>      
        <%= f.label :apellido_cli,"Apellido " %> 
        <%= f.input_field :apellido_cli%>
        <% if @client.errors[:apellido_cli].any? %>
          <p class="text-danger"><%= @client.errors[:apellido_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :apellido2_cli,"Segundo Apellido "%> 
        <%= f.input_field :apellido2_cli%>
      </div>

      <div>      
        <%= f.label :tel_cli,"Télefono " %> 
        <%= f.input_field :tel_cli%>
        <% if @client.errors[:tel_cli].any? %>
          <p class="text-danger"><%= @client.errors[:tel_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :correo_cli,"Correo Eléctronico "%> 
        <%= f.input_field :correo_cli%>
        <% if @client.errors[:correo_cli].any? %>
          <p class="text-danger"><%= @client.errors[:correo_cli].first %></p>
        <% end %>
      </div>

      <div>      
        <%= f.label :direccion_cli,"Dirección "%>
        <%= f.input_field :direccion_cli%>
        <% if @client.errors[:direccion_cli].any? %>
          <p class="text-danger"><%= @client.errors[:direccion_cli].first%> </p>
        <% end %>
      </div>
    </section>

    <section class="botonesNew">
      <%= f.button :submit,"Actualizar", class:"crearClientes"%>
    </section>    
  </main>
<% end %>

rails/SISMU/app/views/clients/index.html.erb
<main class="container sombra">
  <section class="productos">
    <%# <div class="box">
        <%= form_tag clients_path, :method => 'get' do 
        <p>
          <%= text_field_tag :search, params[:search] 
          <%= submit_tag "Buscar", :id => nil  
        </p>
      <% end 
    </div> %>

    <div class="buscador_client">
      <div class="prueba_client">
        <%= form_tag clients_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: "Buscar"%>
          <div class="btn_buscar_client">
            <button class="btn_borrar">
              <%= image_tag "iconos/buscar_blanco", :referencia_pro => nil, class: "logoBuscar_client" %>
            </button>
          </div>
        <% end %>
      </div>
    </div>

    <h1 class="clientes__titulo">Clientes</h1>
      <%= link_to new_client_url do %>
        <div class="clientes__nuevo">
          <p>Nuevo</p>
        </div>
      <% end %>
  </section>

  <section class="clientesTable">
    <table>
      <thead>
        <tr>
          <th><%= sort_link(@q, :id,"Cedula", default_order: :desc, class:"white") %></th>
          <th><%= sort_link(@q, :nombre_cli,"Primer Nombre", default_order: :desc, class:"white") %></th>
          <th><%= sort_link(@q, :apellido_cli,"Primer Apellido", default_order: :desc, class:"white") %></th>
          <th colspan="3">Acción</th>
        </tr>
      </thead>
      <tbody>
        <%= render @clients%>
      </tbody>
    </table>
  </section>

  <div class="digg_pagination">
    <%= will_paginate(@productos,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0) %>
  </div>

</main>

rails/SISMU/app/views/clients/new.html.erb
<%= render "form"%>

rails/SISMU/app/views/clients/show.html.erb
<main class= "clientesShow sombra">

     <section class = "botonEliminarShow">
          <%= button_to "Eliminar",@client, method: :delete, class: "btn_borrar, eliminar", onclick: "return confirmDestroy('¿Deseas eliminar este cliente?')" %>
     </section>

     <h1>Información Cliente</h1>
   

    <section class= "informacionClientes">
          <div>
               <label>Cedula</label>
               <input type="text" value="<%= @client.id %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
          <div>
               <label>Primer Nombre</label>
               <input type="text" value="<%= @client.nombre_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
     </section>

     <section class="informacionClientes">
          <div>
               <label>Telefono</label>
               <input type="text" value="<%= @client.tel_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
          <div>
               <label>Segundo Nombre</label>
               <input type="text" value="<%= @client.nombre2_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
     </section>

     <section class="informacionClientes">
          <div>
             <label>Correo Electronico</label>
             <input type="text" value="<%= @client.correo_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
          <div>
             <label>Primer Apellido</label>
             <input type="text" value="<%= @client.apellido_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
     </section>

     <section class="informacionClientes">
          <div>
               <label>Direccion</label>
               <input type="text" value="<%= @client.direccion_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
          <div>
               <label>Segundo Apellido</label>
               <input type="text" value="<%= @client.apellido2_cli %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
     </section>

     <section  class="informacionClientes">
          <div>
             <label>Ciudad</label>
             <input type="text" value="<%= @client.ciudad %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
          <div>
             <label>Barrio</label>
             <input type="text" value="<%= @client.barrio %>" name="cantidad" id="cantidad" disabled=»disabled» />
          </div>
    </section>

    <section class="botonVolver"><%= link_to "Volver", clients_url, class: "volver" %></section>
    
    
   

</main>



   <script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>