rails/SISMU/config/routes.rb
Rails.application.routes.draw do
  get 'configs/index'
  get 'configs/new'
  namespace :emfacturas do
    get 'emdetalles/create'
  end

  get 'emfacturas/index'
  get 'emfacturas/show'
  get 'emfacturas/new'

  # Clientes
  resources :clients

  # MATERIALES
  resources :materials do
    resources :materials_productos, module: :materials
  end

  # CATEGORIA
  resources :categories do
    resources :categories_productos, module: :categories
  end

  #PRODUCTO
  resources :productos do
    resources :categories_productos,module: :productos
  end

  # PEDIDOS FACTURAS
  resources :facturas do
    resources :detalles, module: :facturas, only: [:create ,:destroy]
  end
  
  #colors
  resources :colors

  resources :profiles

  #artesanos
  resources :artesanos
  
  #produccion
  resources :productions do
    resources :dproductions, module: :productions, only:[:create, :destroy]
  end
 
  #empresas
  resources :empresas

  #facturas empresas

  resources :emfacturas do
    resources :emdetalles, module: :emfacturas, only:[:create, :destroy]
  end
  #configuración
  resources :configs
  #HOME
  root to: "home#index"
  
  #DEVISE
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

rails/SISMU/app/models/color.rb
class Color < ApplicationRecord
    has_and_belongs_to_many :detalles
    has_and_belongs_to_many :emdetalles


    validates :tipo, presence: {:message => "«Este campo es obligatorio»"}
    validates :tipo, uniqueness: {:message => "«Este nombre de color ya se encuentra en uso»"}
    validates :tipo, format: { with: /\A[a-zA-ZÀ-ÿ\s]+$\z/, :message => "«Se permiten solo letras» (no se permiten carácteres especiales o espacios)" }
end

rails/SISMU/app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :authenticate_user!
  def index
    @colors = Color.all
    authorize @colors
   end
  def show
    @color = Color.find(params[:id])
    authorize @color
  end
  
  def new
    @color = Color.new
    authorize @color
  end

  def create
    @color = Color.new(color_params)
    if @color.save 
      flash[:alert] = "Se creo correctamente."
      redirect_to colors_path
    else
      render :new
    end
  end
  
  def edit
    @color = Color.find(params[:id])
  end


  def update
    @color = Color.find(params[:id])
    if @color.update(color_params)
      redirect_to colors_path
    else
        render :edit
    end
  end

  def destroy
    @color = Color.find(params[:id]).destroy
    redirect_to colors_path

  end

  private

    def color_params
      params.require(:color).permit(:tipo)
    end
end

rails/SISMU/app/helpers/colors_helper.rb
module ColorsHelper
end

rails/SISMU/app/views/colors/_color.html.erb
<tr>
  <td data-label="Referencia", class="centrar blue">
    <%= color.tipo %>
  </td>

  
  <td data-label="Accion" class="botones blue">
    <%= link_to edit_color_url(color) do %>
      <%# image_tag("iconos/editar", class:"icon_accion") %>
      <button class="editar">Editar</button>
    <% end %>

    <%= button_to "Eliminar",color_path(color), method: :delete, class: "btn_borrar, eliminar", onclick: "return confirmDestroy('¿Deseas eliminar este artesano?')" %>
    
  </td>
</tr>

<script>
  function confirmDestroy(message) {
    if(!confirm(message)){
      return false
    }
  }
</script>

rails/SISMU/app/views/colors/_form.html.erb
<%= simple_form_for @color do |f| %> <br>
<main class="productosNew sombra div_conf">
  <section class="botonVolverNew"><%= link_to "Volver", colors_url, class: "volverNew" %></section>
  <h1>Crear color</h1>

   <section  class="informacionNewConf">
      <div>
           <%= f.label :tipo, 'Escriba el color', required: true %>
           <%= f.input_field :tipo %> 
            <% if @color.errors[:tipo].any? %>
            <p class="text-danger"><%= @color.errors[:tipo].first %> </p>
           <% end %>
      </div>
  </section>
   <section> 
        <div class="botonesNew "><%= f.button :submit, 'Crear', class: "formulario_boton" %></div>
        <br>
   
   </section>

</main>
  <% end %>

rails/SISMU/app/views/colors/index.html.erb
<main class="container sombra">
  <section class="productos">
    <div class="buscador">
      <div class="prueba">
        <%= form_tag productos_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: "Buscar"%>
          <div class="btn_buscar">
            <button class="btn_borrar">
              <%= image_tag "iconos/buscar_blanco", :referencia_pro => nil, class: "logoBuscar" %>
            </button>
          </div>
        <% end %>
      </div>
    </div>

    <h1 class="productos__titulo">Colores</h1>
    <div class="productos__nuevo">
      <%= link_to new_color_url do %>
        <p>Nuevo</p>
      <% end %>
    </div>    
  </section>
    
  <section class= "productosTable">
    <table>
      <thead>
        <tr>
          <th>Tipo de Color</th>
          <th colspan="3">Acción</th>
        </tr>
      </thead>
      <tbody>
        <%= render @colors  %>
      </tbody>
    </table>
  </section>

</main>

rails/SISMU/app/views/colors/show.html.erb
<h1>Colors#show</h1>
<p>Find me in app/views/colors/show.html.erb</p>